janus_ab.config:
  type: config_object
  mapping:
    vendorName:
      type: string
      label: 'The vendor name to use, E.g. "Synetic"'
    siteName:
      type: string
      label: 'The site name to use, E.g. "google"'
    trafficUrl:
      type: string
      label: 'The fully qualified url used for logging traffic'
    successUrl:
      type: string
      label: 'The fully qualified url used for logging success'
    analyticsId:
      type: string
      label: 'The Google Analytics id E.g. "UA-XXXXXXXXX-X"'
    experiments:
      type: mapping
      label: 'The experiments that should be ran. No concurring experiments'
      id:
        type: string
        label: 'The experiment id'
      startDate:
        type: string
        label: 'Experiment start date, format: dd-mm-yyyy'
      endDate:
        type: string
        label: 'Experiment end date, format: dd-mm-yyyy'
      variations:
        type: mapping
        label: 'The variations for this experiment'
        id:
          type: string
          label: 'The variation id'
        name:
          type: string
          label: 'The variation name'